### ISSUE TITLE
贡献一点点需求的小小意见

### ISSUE THREAD

**Issue by JoshuaQYH** [sysu-change/Dashboard#5]
首先表扬一下整体UI和功能都做得挺完备挺OK哒！
个人觉得可以考虑加一个任务回收站之类的，万一某些任务撤销之后，在今后的某一个时间段还需要再次启用嘛，做软删除后面还可以快速恢复再次修改呢嘻嘻；
还有就是登陆方面可以考虑加一个忘记密码怎么办哈哈哈，毕竟可能某些人资产挺多的，忘记密码怎么补救哈哈哈~

**Comment by Chenxr1997** [comment]
说的很有道理，后续版本看一看～
