### ISSUE TITLE
关于UI设计的一些意见（我又来啦哈哈哈~~~）

### ISSUE THREAD

**Issue by JoshuaQYH** [sysu-change/Dashboard#6]
看了演示的视频，发现问卷创建编辑的时候，UI风格明显和其他地方差别有点大，貌似不是用的Element UI，建议保持风格统一~~

**Comment by Chenxr1997** [comment]
是滴，居然被发现了(*゜ェ゜*)，当时我也被惊呆了。这大概是因为，，经费不够了_(:з」∠)_
